server:
  port: 80
file:
  upload-dir: uploads/
firebase:
  url-bucket: set url bucket
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://test:3306/auto_frota
    username: set username
    password: set password
  flyway:
    enabled: true
  mail:
    host: smtp.test.com
    port: 587
    username: set email
    password: set password
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
  redis:
    host: set host
    port: set port