server:
  port: 80
file:
  upload-dir: uploads/
firebase:
  url-bucket: storage firebase
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://testehost:3306/auto_frota
    username: username
    password: password
  flyway:
    enabled: true
