server:
  port: 80
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://teste:3306/auto_frota
    username: username
    password: password
  flyway:
    enabled: true
