server:
  port: 8080
file:
  upload-dir: uploads/
firebase:
  url-bucket: set url bucket
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/auto_frota
    username: set username
    password: set password
  flyway:
    enabled: true
  mail:
    host: smtp.test.com
    port: set port
    username: set username
    password: set password
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
  redis:
    host: set host
    port: set port
mercado-pago:
  access-token: set access token
  public-key: set public key
  webhook:
    secret: set secrete